version: '3'
services:
  web:
    build:
      context: ./php
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./handson:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_DATABASE: handson
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
      